### ISSUE TITLE
[EmbedUtils] Edit command should have a channel option

### ISSUE THREAD

**Issue by Nogooduser** [phenom4n4n/phen-cogs#114]
Currently the only way to edit an existing embed is to send a message in the same channel it was posted.

There should be a way to specify a channel so that the edit command can be sent from a private channel. 
 Something like ``.embed edit json <channel> <data>``  
This would of course apply to all types of edits like ``fromfile``, ``pastebin``, etc.

The use case for this is when you have embeds in announcement-type channels where only mods can post and don't want to post a new command there that will needlessly alert regular users.

The regular embed command already supports a channel parameter, so it only feels logical that the edit command would too.

**Comment by sravan1946** [comment]
You can edit the embeds in other channel by using a combination of the channel id and message id. Press and hold the shift button and click on the ID icon to get that. or you can just manully type it like `CHANNELID-MESSAGEID` with the - in between.

**Comment by Nogooduser** [comment]
Ah, the command didn't specify it so I didn't know.

In the meantime during my testing I also discovered that using the direct url for the message also works.

Closing the issue. Thank you!
