### ISSUE TITLE
[Aki] Aki fails at question 80

### ISSUE THREAD

**Issue by fixator10** [phenom4n4n/phen-cogs#119]
After question 80, Aki fails, raising unhandled AkiNoQuestions, all menu buttons after that becomes unresponsive: buttons gets acknowledged (no "failed" discord button text), but nothing happens.

https://sentry.io/share/issue/ff48b8b1a3514c898e9dcb2ab437c422/
https://sentry.io/share/issue/778a4d6bded64928ab052ce95cf4b6a4/

**Comment by DJTOMATO** [comment]
I second this, also happens to me

error log here
https://pastebin.com/jwHpswxC

**Comment by phenom4n4n** [comment]
This should be resolved in https://github.com/phenom4n4n/phen-cogs/commit/466c995b7ee3e53e020da64ffa711b44261822a6.
