### ISSUE TITLE
[RoleUtils] Add option for removing invalid reactions in reactroles.

### ISSUE THREAD

**Issue by Flightkick** [phenom4n4n/phen-cogs#126]
Users can react with invalid emoji's causing the list of options to be cluttered. It would be nice if the bot automatically removes invalid (non-bound) reactions.

**Comment by zephyrkul** [comment]
Just deny the Add Reactions permission in that channel. Users will still be able to use already existing reactions but won't be able to add new reactions.

**Comment by Flightkick** [comment]
Ah fair, that will do. Thanks!
