### ISSUE TITLE
[EmbedUtils] Add An Option To Edit Embed Messages

### ISSUE THREAD

**Issue by J-Daniel-1** [phenom4n4n/phen-cogs#14]
# Feature Request

If someone needed to edit an embed that has role reactions attached to the message, being able to edit the embed without needing to resend the embed and having to redo all of the said role reactions would make it a lot more convenient and it makes more logical sense.

Something like `[p]embed edit <message_id> <fromfile/frommsg/fromdata/etc.>`

**Comment by J-Daniel-1** [comment]
I believe you can edit webhook embeds as well so maybe do the same thing for webhook embeds?

**Comment by J-Daniel-1** [comment]
_I don't like bumping issues but here I am.._

**Comment by phenom4n4n** [comment]
Closing this as `[p]embed edit` has been added.
