### ISSUE TITLE
deactive message that it was completed

### ISSUE THREAD

**Issue by 08shiro80** [phenom4n4n/phen-cogs#140]
a Parameter or something to deactive this message if its all working, i didnt find it to deactivate if its implemented.
and thanks for this cog

**Comment by phenom4n4n** [comment]
Hello, this issue is incomprehensible. I don't know which cog or feature you are referring to.

**Comment by 08shiro80** [comment]
ah sorry, i mean slashtags 
![Screenshot_20221008-145955_Discord](https://user-images.githubusercontent.com/64030121/194708906-5c38464b-2322-40c2-a50e-fe834eb2c231.jpg)
![Screenshot_20221008-150124_Discord](https://user-images.githubusercontent.com/64030121/194708917-f2d25aa3-0fac-4d89-8a8a-248f6941f2b0.jpg)

**Comment by 08shiro80** [comment]
to note that i didn't get the command to work with that the number argument as number formattet (so i set it to string and it worked then)
![Screenshot_20221008-151523_Discord](https://user-images.githubusercontent.com/64030121/194709467-cd7c734b-8a92-46e0-9eb0-9c971a0a7623.jpg)

**Comment by phenom4n4n** [comment]
This is intended behavior. If the "completed" response were not sent, it would visually appear as though the interaction had errored out.
