### ISSUE TITLE
[aki] wrong repo url

### ISSUE THREAD

**Issue by NoPlagiarism** [phenom4n4n/phen-cogs#147]
[This line (aki.py:98)](https://github.com/phenom4n4n/phen-cogs/blob/1dd11e0775c8433b188df1db135d0e6dfa13f46a/aki/aki.py#L98) needs editing

`NinjaSnail1080` moved to `Infiniticity`

https://github.com/Infiniticity/akinator.py

**Comment by NoPlagiarism** [comment]
Oh... And also, there no languages on ReadMe. So now it should be

https://akinator.readthedocs.io/en/latest/#functions

**Comment by phenom4n4n** [comment]
Resolved by f0faf22197e13606aba71a5c9762d0fc8cd01423
