### ISSUE TITLE
[LinkQuoter] Suggestion | Delete Invoking Link Message

### ISSUE THREAD

**Issue by Menteroth** [phenom4n4n/phen-cogs#16]
An option to choose to delete the link that was sent and add the user into the embed that sent the message link.
Like something similar to how `translate` does it. So you don't have to have that long ass link on top of the embed. Since the embed has a jump link in it.

`Requested by User#0001`
![image](https://user-images.githubusercontent.com/24851042/103146616-89357280-474c-11eb-8904-b335490a323b.png)

**Comment by phenom4n4n** [comment]
This has been added in the last update, you can enable it for `[p]linkquote delete`. As for showing the user who sent the link, this can be seen by loading my webhook cog and enabling webhooks for linkquoting with `[p]linkquote webhook`.
