### ISSUE TITLE
[LinkQuoter] Quoting an Embed duplicates "Replying to" and "Source" sections

### ISSUE THREAD

**Issue by T14D3** [phenom4n4n/phen-cogs#162]
Title, both "Replying to" and "Source" sections (including the links) get "increased" by one every time the original embed message is quoted.
Example attached below
![image](https://user-images.githubusercontent.com/73843330/232473493-9b308a18-3c7f-4602-b123-504560d261b8.png)

**Comment by phenom4n4n** [comment]
Resolved by 2c901c0,
