### ISSUE TITLE
[aki] Doesn't work on Redbot 3.5.1

### ISSUE THREAD

**Issue by rex2630** [phenom4n4n/phen-cogs#167]
May 07 13:45:14 ubuntu python[273087]: [2023-05-07 13:45:14] [ERROR] red: Package loading failed
May 07 13:45:14 ubuntu python[273087]: Traceback (most recent call last):
May 07 13:45:14 ubuntu python[273087]:   File "/home/ubuntu/redenv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 188, in _load
May 07 13:45:14 ubuntu python[273087]:     await bot.load_extension(spec)
May 07 13:45:14 ubuntu python[273087]:   File "/home/ubuntu/redenv/lib/python3.11/site-packages/redbot/core/bot.py", line 1680, in load_extension
May 07 13:45:14 ubuntu python[273087]:     lib = spec.loader.load_module()
May 07 13:45:14 ubuntu python[273087]:           ^^^^^^^^^^^^^^^^^^^^^^^^^
May 07 13:45:14 ubuntu python[273087]:   File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
May 07 13:45:14 ubuntu python[273087]:   File "<frozen importlib._bootstrap_external>", line 1120, in load_module
May 07 13:45:14 ubuntu python[273087]:   File "<frozen importlib._bootstrap_external>", line 945, in load_module
May 07 13:45:14 ubuntu python[273087]:   File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
May 07 13:45:14 ubuntu python[273087]:   File "<frozen importlib._bootstrap>", line 721, in _load
May 07 13:45:14 ubuntu python[273087]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
May 07 13:45:14 ubuntu python[273087]:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
May 07 13:45:14 ubuntu python[273087]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
May 07 13:45:14 ubuntu python[273087]:   File "/home/ubuntu/.local/share/Red-DiscordBot/data/Davidb/cogs/CogManager/cogs/aki/__init__.py", line 30, in <module>
May 07 13:45:14 ubuntu python[273087]:     from .aki import Aki
May 07 13:45:14 ubuntu python[273087]:   File "/home/ubuntu/.local/share/Red-DiscordBot/data/Davidb/cogs/CogManager/cogs/aki/aki.py", line 28, in <module>
May 07 13:45:14 ubuntu python[273087]:     import akinator
May 07 13:45:14 ubuntu python[273087]: ModuleNotFoundError: No module named 'akinator'
May 07 13:45:25 ubuntu python[273087]: [2023-05-07 13:45:25] [INFO] discord.gateway: Shard ID 0 has successfully RESUMED session b430b5ea3bd205e37244bc86ae8654c4.

**Comment by rex2630** [comment]
This log is from dpy2 branch

**Comment by sravan1946** [comment]
Try reinstalling or do `[p]pipinstall akinator[fast_async]==1.0.3`

**Comment by rex2630** [comment]
![image](https://user-images.githubusercontent.com/30006554/236682188-3a64f471-47e9-4625-ae89-2f4796a736ab.png)

**Comment by sravan1946** [comment]
traceback for that?

**Comment by rex2630** [comment]
May 07 14:15:29 ubuntu python[273087]: [2023-05-07 14:15:29] [ERROR] red.downloader: error: subprocess-exited-with-error
May 07 14:15:29 ubuntu python[273087]:
May 07 14:15:29 ubuntu python[273087]:   × python setup.py bdist_wheel did not run successfully.
May 07 14:15:29 ubuntu python[273087]:   │ exit code: 1
May 07 14:15:29 ubuntu python[273087]:   ╰─> [23 lines of output]
May 07 14:15:29 ubuntu python[273087]:       running bdist_wheel
May 07 14:15:29 ubuntu python[273087]:       running build
May 07 14:15:29 ubuntu python[273087]:       running build_py
May 07 14:15:29 ubuntu python[273087]:       creating build
May 07 14:15:29 ubuntu python[273087]:       creating build/lib.linux-aarch64-cpython-311
May 07 14:15:29 ubuntu python[273087]:       creating build/lib.linux-aarch64-cpython-311/cchardet
May 07 14:15:29 ubuntu python[273087]:       copying src/cchardet/version.py -> build/lib.linux-aarch64-cpython-311/cchardet
May 07 14:15:29 ubuntu python[273087]:       copying src/cchardet/__init__.py -> build/lib.linux-aarch64-cpython-311/cchardet
May 07 14:15:29 ubuntu python[273087]:       running build_ext
May 07 14:15:29 ubuntu python[273087]:       building 'cchardet._cchardet' extension
May 07 14:15:29 ubuntu python[273087]:       creating build/temp.linux-aarch64-cpython-311
May 07 14:15:29 ubuntu python[273087]:       creating build/temp.linux-aarch64-cpython-311/src
May 07 14:15:29 ubuntu python[273087]:       creating build/temp.linux-aarch64-cpython-311/src/cchardet
May 07 14:15:29 ubuntu python[273087]:       creating build/temp.linux-aarch64-cpython-311/src/ext
May 07 14:15:29 ubuntu python[273087]:       creating build/temp.linux-aarch64-cpython-311/src/ext/uchardet
May 07 14:15:29 ubuntu python[273087]:       creating build/temp.linux-aarch64-cpython-311/src/ext/uchardet/src
May 07 14:15:29 ubuntu python[273087]:       creating build/temp.linux-aarch64-cpython-311/src/ext/uchardet/src/LangModels
May 07 14:15:29 ubuntu python[273087]:       aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Isrc/ext/uchardet/src -I/home/ubuntu/redenv/include -I/usr/include/python3.11 -c src/cchardet/_cchardet.cpp -o build/temp.linux-aarch64-cpython-311/src/cchardet/_cchardet.o
May 07 14:15:29 ubuntu python[273087]:       src/cchardet/_cchardet.cpp:196:12: fatal error: longintrepr.h: No such file or directory
May 07 14:15:29 ubuntu python[273087]:         196 |   #include "longintrepr.h"
May 07 14:15:29 ubuntu python[273087]:             |            ^~~~~~~~~~~~~~~
May 07 14:15:29 ubuntu python[273087]:       compilation terminated.
May 07 14:15:29 ubuntu python[273087]:       error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
May 07 14:15:29 ubuntu python[273087]:       [end of output]
May 07 14:15:29 ubuntu python[273087]:
May 07 14:15:29 ubuntu python[273087]:   note: This error originates from a subprocess, and is likely not a problem with pip.
May 07 14:15:29 ubuntu python[273087]:   ERROR: Failed building wheel for cchardet
May 07 14:15:29 ubuntu python[273087]: ERROR: Could not build wheels for cchardet, which is required to install pyproject.toml-based projects
May 07 14:15:29 ubuntu python[273087]: [2023-05-07 14:15:29] [ERROR] red.downloader: Something went wrong when installing the following requirements: akinator[fast_async]==1.0.3

**Comment by sravan1946** [comment]
It seems like that error is a [bug](https://github.com/cython/cython/issues/4461) in python3.11

**Comment by sravan1946** [comment]
Try doing `[p]pipinstall cchardet` first and then use `[p]pipinstall akinator[fast_async]==1.0.3`

**Comment by rex2630** [comment]
i have tried almost anything, but it seems that there is just problem in TA-lib with python 3.11

**Comment by sravan1946** [comment]
You could come to [phen's support channel](https://canary.discord.com/channels/240154543684321280/825064573308633142) in [red cog support](https://discord.gg/red-cog-support-240154543684321280) server so i can support you more easily

**Comment by rex2630** [comment]
pip install cython fixed the issue, thanks for help
