### ISSUE TITLE
[bug ] linkquoter cog slow down the bot.

### ISSUE THREAD

**Issue by mina9999** [phenom4n4n/phen-cogs#27]
hi i have 20 cogs loaded in my bot but when i load linkquoter cog the bot is super slow for me and it hang really bad.
but when i unload linkquoter cog the bot is fast again. idk whats wrong for real. there is no error in my console too.
can u guys please fix this thank you.<333
my bot was slow yesterday and i unload and load all cogs 1 by 1 and i found out this.

**Comment by phenom4n4n** [comment]
Hello,
LinkQuoter on my bot runs smoothly and has no adverse effects on it. It has a light regex match on each message which is used if LinkQuoter auto is enabled, but this should not affect your bot unless the machine it runs on has low ram. There's no fix I can make for this, and the only recommendation I have is to look into upgrading your host.
