### ISSUE TITLE
[RoleUtils] !reactrole create throws an error when trying to create an embed in a different channel

### ISSUE THREAD

**Issue by Jademalo** [phenom4n4n/phen-cogs#31]
I have my bot as part of a role which has the `Manage Roles` permission enabled, but not Administrator.
For some reason, I run into a lot of issues when a channel is specified.

`!reactrole create :regional_indicator_h:;@He/Him #role-assignment Blue`
This command uses an existing role. I get the response `Error in command 'reactrole create'. Check your console or logs for details.`
```[2021-02-22 22:17:35] [ERROR] red: Exception in command 'reactrole create'
Traceback (most recent call last):
  File "/home/jademalo/.pyenv/versions/MTGPLBot/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/jademalo/MTGPLBot/cogs/CogManager/cogs/roleutils/reactroles.py", line 183, in reactrole_create
    message = await channel.send(embed=e)
  File "/home/jademalo/.pyenv/versions/MTGPLBot/lib/python3.8/site-packages/discord/abc.py", line 935, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/home/jademalo/.pyenv/versions/MTGPLBot/lib/python3.8/site-packages/discord/http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
```
This seems to be a simple missing permissions error, but it doesn't make a whole lot of sense since the bot should have the manage roles permission. In addition, it's not making a new role, so I've got absolutely zero idea why it would need any additional permissions.
Giving the bot the full Administrator permission results in this working correctly.

`!reactrole create :regional_indicator_h:;@He/Him Blue`
This command works correctly, so long as the command is invoked from the correct channel. It seems that the first command breaks due to it failing to place the role into a different channel? I'm not really sure.

_________

Hopefully these cases are clear enough, I'm not really sure why this is happening. I can just about get the functionality I want by invoking it in the specific channel to begin with, but there's clearly something going wrong here. It will also sometimes just display the `!reactrole create` help menu, and I've got no idea why it does that.

**Comment by phenom4n4n** [comment]
Your bot is missing permissions to send messages in the specified channel. The latest commit will throw a user-friendly error if lacking permissions.

**Comment by Jademalo** [comment]
Turns out someone had changed the permission structure of the channel without my knowledge. My bad, thought I was going insane.
