### ISSUE TITLE
[Feature Request] Embedutils

### ISSUE THREAD

**Issue by Merp-Me** [phenom4n4n/phen-cogs#32]
For the Embedutils cog, it would be convenient to view the stored embeds format in a code block. Another very useful change would be to be able to send stored embeds to specified channels. I dont believe there is an option for that yet, there is only a show one which could do the same thing but its more useful if using it in larger servers.

**Comment by phenom4n4n** [comment]
Hello,
Thanks for the ideas, you can now download a stored embed's JSON with `[p]embed store download <name>`. Additionally, a channel option has been added to the `[p]embed post <name> [channel]` command.
