### ISSUE TITLE
[EmbedUtils] Add Message Content Support

### ISSUE THREAD

**Issue by Jac0bDan13L** [phenom4n4n/phen-cogs#38]
It would be cool if you could add message support to this cog as I find it useful as would many others that uses this cog.

**Comment by phenom4n4n** [comment]
Message content support has been added in the latest update to the cog. You can add message content in four commands: `embed json`, `embed yaml`, `embed jsonfile` `embed yamlfile` by adding a key to your data called content.

Examples: 
```
[p]embed yaml content: message content
title: embed title
```
```
[p]embed json {"content": "message content", "title": "embed title"}
```
