### ISSUE TITLE
[EmbedUtils] add YAML support for embed input

### ISSUE THREAD

**Issue by XangelMusic** [phenom4n4n/phen-cogs#43]
When trying to use Retrigger from Trusty-Cogs with the fromdata command, the {attachment.url} isn't replaced with the posted image attachment URL. I use this to trigger a response to images posted in discord as an embedded message with a link to SauceNAO but the link always returns as: https://saucenao.com/search.php?db=999&url={attachment.url}

**Comment by phenom4n4n** [comment]
The bracketing issue described here would be resolved by adding yaml support rather than solely json to embedutils.

**Comment by phenom4n4n** [comment]
YAML data and file support has been added to the regular, storage, editing, and webhook commands in the latest update to the cog.
