### ISSUE TITLE
[Disboard reminder] lock setup

### ISSUE THREAD

**Issue by ReubenDollmanYT** [phenom4n4n/phen-cogs#50]
For the lock command add a sub command like role [mention/id] as some servers have member roles so locking the everyone role wont lock the chanel
so the end comand would look like this
[p]bumpreminder lock role {id}

**Comment by phenom4n4n** [comment]
If your server permission requires a role-specific override to send messages in a channel, then your server permissions have been configured tediously and inefficiently. I will not be adding support for this as the better option is to create the proper server permissions.
