### ISSUE TITLE
[Baron] Feature request: Add a "whitelist only" mode.

### ISSUE THREAD

**Issue by Jacob-1999** [phenom4n4n/phen-cogs#54]
There's no setting to set a "whitelist only" mode. Having no setting but a whitelist makes the whitelist useless since there's nothing about the cog that utilizes the whitelist. It's just there. 

It would be cool to have a "whitelist only" mode as with my bot I allow people to invite my bot via requests and then whitelisting servers the bot can do in so I don't have to do any extra work like serverlocking, etc.

**Comment by phenom4n4n** [comment]
The whitelist is utilized to prevent the bot from leaving whitelisted servers during auto server leaves or mass server leaves. If you want the bot to only be able to join whitelisted servers, set the server limit to 1 (`[p]baron limit 1`).
