### ISSUE TITLE
AltDentifier check failed

### ISSUE THREAD

**Issue by brysonchase43** [phenom4n4n/phen-cogs#70]
Hey, can you please fix the altdentifier? It keeps failing to check the users. 

![](https://cdn.discordapp.com/attachments/836647702543728720/847219941156716595/image0.png)

**Comment by phenom4n4n** [comment]
You've been told countless times that you aren't welcome to use Red, yet you keep on relentlessly harassing us with your alts.  I'll be reporting you to GitHub and won't provide you support for my cogs.
