### ISSUE TITLE
Prefix command Abuse.

### ISSUE THREAD

**Issue by Lime007** [phenom4n4n/phen-cogs#71]
As u know , ur cog for prefix cmd manage ment is great but it needs to be fixed as people can abuse and cause errors to it , u can make a prefix how long u want (even 2000+ chars) which causes the prefix view command to bug and give a error ... the solution is to make the max prefix length to 10 character or so ... this applies for noumenon as well .. and also I pinged u in ur server to tell u but u banned as I felt it was important .. 
![image](https://user-images.githubusercontent.com/75667833/120086399-a1d8f880-c0ef-11eb-9878-b947a2a3f000.jpeg)

**Comment by andyp-tm** [comment]
This as far as i am aware will only affect the server that has added the incredibly stupid prefix.

I would only assume that if, as with any command if it is abused it would result in a user/server bot ban.

**Comment by Lime007** [comment]
> This as far as i am aware will only affect the server that has added the incredibly stupid prefix.
> 
> I would only assume that if, as with any command if it is abused it would result in a user/server bot ban.

Ik ur right but is there not any way to limit a prefix like Karl bot etc to max of 5 prefixes per guild .. my point was not to abuse but inform ..  as if someone does it then u see there's now way of redacting .l also the length of the prefix should be a max of 10chars .. what do u say ?

**Comment by phenom4n4n** [comment]
This concerns and should be implemented in the core bot settings and not my prefix cog.

**Comment by Lime007** [comment]
> This concerns and should be implemented in the core bot settings and not my prefix cog.

Alright thanks! got it ... i had informed the support and it will be mostly implemented in update 3.5 or so
