### ISSUE TITLE
[Webhooks] A option to Disable Pings

### ISSUE THREAD

**Issue by ReubenDollmanYT** [phenom4n4n/phen-cogs#78]
would there be a way to edit the webhook sesion cog so there is a setting to disable pings crossing both servers as this could esaly be used to raid and could get quite anoying

**Comment by phenom4n4n** [comment]
1. The webhook session command requires a webhook link, and anyone with access to the webhook link can role/everyone ping, regardless of what program they use with the link.
2. Role/everyone pings are already disabled on all webhook commands.
