### ISSUE TITLE
[BanChart] Reported ban number is not equal to the number of bans in the chart

### ISSUE THREAD

**Issue by Flame442** [phenom4n4n/phen-cogs#79]
Banchart uses `len(await ctx.guild.bans)` to determine how many bans there are for the header of the image, however the audit log can have a different number of ban events in many cases. If a user is unbanned, they will not be in `ctx.guild.bans`, but a ban audit log case may remain for them. Also, audit log cases expire after a while, so a ban might exist with no audit log case. For this reason, I suggest tracking the number of bans as you iterate over them, then putting *that* number in the image. The "Gathering stats for the last {limit} bans.` text can probably continue to use the naive `len(await ctx.guild.bans)` calculation.

**Comment by phenom4n4n** [comment]
Thanks for reporting this discrepancy, it has been fixed in the latest update.
