### ISSUE TITLE
[EmbedUtils] Suggestion: Be Able to Pass Channel When Storing an Embed From Message -nt-

### ISSUE THREAD

**Issue by Menteroth** [phenom4n4n/phen-cogs#8]
nt

**Comment by phenom4n4n** [comment]
This is already possible, by using a message link to reference the embed from a message.

**Comment by Menteroth** [comment]
Oh okay. Wasn't obvious from the help. I thought `<message>` was only same channel since message ID outside of input channel didn't work. Thanks.
