### ISSUE TITLE
tags: migratecustomcom should convert 0-index to 1-index

### ISSUE THREAD

**Issue by synrg** [phenom4n4n/phen-cogs#81]
After `[p]migratecustomcom`, any of my former cc's that had {0}...{1} in them are converted to tags with args(0)...args(1). However, that's incorrect, as customcom is 0-indexed. It should output args(1)...args(2), etc.

**Comment by synrg** [comment]
Caution: this is not *just* an off-by-one error. CustomCommands has the special behaviour for {0} that if it's the only argument in the customcom, it is treated as args(0). So the off-by-one correction only needs to be applied if there's more than one argument.

**Comment by phenom4n4n** [comment]
This should be resolved now. TagScript is 1-indexed, but the special casing you mentioned is because indexing a single entry list by 0 or -1 returns the same value in Python, so in TagScript `{args(0)}` and `{args(1)}` will return the same string if only one argument is passed..
