### ISSUE TITLE
tags: please use code formatting for raw subcommand output

### ISSUE THREAD

**Issue by synrg** [phenom4n4n/phen-cogs#82]
Please have `[p]tag raw` and `[p]tag global raw` subcommands use code formatting for their output so that if the production of the tag is a URL, it won't be subject to Discord's URI-quoting, which mangles the result.

For example, a tag that simply outputs a link like `https://...{args(1)}` is detected by Discord as a URL and thus rendered as `https://...%7Bargs(1)%7D` which makes it very hard to understand. For the user to be able to make any use of it, they then need to manually convert that back to actual curly-braces (as when cuttting-and-pasting to use it in another command).

**Comment by synrg** [comment]
Example `[p]tag raw` output that looks pretty terrible, and also hides the fact that the definition has angle-brackets around the URL to suppress Discord's automatic preview.

![image](https://user-images.githubusercontent.com/1204376/125934555-87de8356-583e-47ea-9570-7f3817efffad.png)

Mockup of how I think it should look instead:

![image](https://user-images.githubusercontent.com/1204376/125934878-f8c6be07-91d4-4c32-9a59-010e4b18488b.png)

**Comment by phenom4n4n** [comment]
This has been implemented in the latest update to Tags and SlashTags.
