### ISSUE TITLE
[RoleUtils] Add nickname or @mentions without notification when looking up users with a role

### ISSUE THREAD

**Issue by NNTin** [phenom4n4n/phen-cogs#89]
![image](https://user-images.githubusercontent.com/18033169/126970028-25318ac4-f454-4180-9603-ac93dc8a127b.png)
The command `[p]role members @role` lists all members with the role however it is hard to make the connection who the discord Members are since they often have a guild unique nickname.

Suggestion: add nickname or a @mention without ping notification

**Comment by phenom4n4n** [comment]
Hello, in the latest update to RoleUtils you can now supply a custom formatting string to format the member names. For example, to show their mention or display name, you could use one of the following methods:
`[p]role members @role {member(display_name)} - {member(id)}`
`[p]role members @role {member(mention)}`
You can also do other cool stuff like formatting user timestamps! See the command help for more information as well as a link to documentation on the member block.
![image](https://rickroll.click-if-you-da.re/59qUe09U3.png)
