### ISSUE TITLE
[EmbedUtils] Suggestion: Able to Edit a Message to Replace an Embed with Another in a Message

### ISSUE THREAD

**Issue by Menteroth** [phenom4n4n/phen-cogs#9]
Like unapproved EmbedMaker has `editmsg`.

**Comment by phenom4n4n** [comment]
I'm not that motivated to do this since I see chances of breaking other commands on my bot and personally would disable such a command. I'll leave this open for someone else to PR, else I might look at it in a few weeks, but no guarantee.

**Comment by phenom4n4n** [comment]
Closing this as `[p]embed edit` has been added.
